<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="completed">
	<h2><mark>Final advice</mark></h2>

	<dl>
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
	
	
	<form>
		 <input type="button" onclick="location.href='https://pacemakeradvice.herokuapp.com/index.php';" value="Start over" />
	</form>
</section>
<?php $this->end() ?>
