<!DOCTYPE html>
<html>
	<head>
		<title>Pacemaker advice</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="kennisbanken">
		<nav class="site-nav">
			<!-- what should come here? -->
		</nav>

		<header>
			<img src="download.png" width="100" height="100">
			<h1>Advice for patients with a Pacemaker, ICD, or ILR</h1>
			<p>Using a series of questions this expert system gives a reccommendation
				as to how a patient should react to the symptoms and trouble they are
				having with their implant. To start the survey press the button below.</p>
		</header>


		<?php if ($errors): ?>
		<section class="status-update">
			<p>The following errors occurred:</p>
			<ul>
				<?php foreach ($errors as $error): ?>
				<li title="<?=$this->attr(sprintf('%s:%d', $error->file, $error->line))?>"><?=$this->html($error->message)?></li>
				<?php endforeach ?>
			</ul>
		</section>
		<?php endif ?>
		
		<section class="upload-knowledge-base-form">
			<form method="post" enctype="multipart/form-data">
				<div class="controls">
					<button type="submit" name="action" value="run">Start</button>
				</div>
			</form>
		</section>

		<footer>
			<p>Artificial cardiac pacemaker icon from <a href="https://stock.adobe.com/de/images/artificial-cardiac-pacemaker-line-icon-outline-vector-sign-linear-style-pictogram-isolated-on-white-symbol-logo-illustration-editable-stroke-pixel-perfect/143432741">adobe stock</a></p>
			<p>Source code available on <a href="https://github.com/jelmervdl/kennissysteem">Github</a>.</p>
		</footer>

		<script>
			Array.prototype.forEach.call(
				document.querySelectorAll("a[href^='#']"),
				function(el) {
					console.log(el);
					el.addEventListener('click', function() {
						var hash = el.href.substring(el.href.indexOf('#') + 1);
						var ref = document.getElementById(hash);
						
						Array.prototype.forEach.call(
							document.querySelectorAll('.highlight'),
							function(node) {
								node.classList.remove('highlight')
							});
						
						if (ref)
							ref.classList.add('highlight');
					});
				});
		</script>
	</body>
</html>
